train:
  n_envs: 4
  frame_skip: 5
  reset_noise_scale: 0.1
  max_episode_steps: 1000
  total_timesteps: 40960000
  checkpoint_freq: 1024000
  custom_log_freq: 2048

demo:
  demo_type: "rgb_array" 
  camera_pos: "0 -1.6 1.3"
  camera_xyaxes: "1 0 0 0 1 1"
  mjc_render_width: 150
  mjc_render_height: 150
  plt_n_lines: 1
  plt_x_range: 100

control:
  control_type: "generate"
  generator_theta: 1.0
  generator_smooth_order: 20
  generator_schedule: [
    {
      "name": "robot_x_velocity",
      "clip": [0.0, 10.0],
      "avg": [0.0, 2.0, 3.0, 2.0, 6.0, 3.0, 7.0, 3.0, 3.0],
      "amp": [0.0, 0.0, 0.0, 4.0, 2.0, 5.0, 3.0, 7.0, 7.0],
    },
    {
      "name": "robot_y_velocity",
      "clip": [-5, 5],
      "avg": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
      "amp": [0.0, 0.0, 0.2, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
    },
    {
      "name": "z_angular_velocity",
      "clip": [-3.14, 3.14],
      "avg": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
      "amp": [0.0, 0.0, 0.2, 0.5, 1.0, 1.0, 1.5, 1.5, 1.5],
    },
  ]

reward:
  alive_weight: 0.2
  illegal_contact_weight: -1.0
  robot_xy_velocity_weight: 5.0
  z_angular_velocity_weight: 2.0
  z_velocity_weight: -2.0
  z_position_weight: -5.0
  xy_angular_velocity_weight: -0.05
  xy_angular_weight: -5.0
  action_change_weight: -0.05
  hinge_angular_velocity_weight: -0.001
  hinge_position_weight: -1.0
  hinge_exceed_limit_weight: -5.0
  hinge_energy_weight: -2.0e-5
  gait_loop_weight: 1.0
  feet_state_duration_weight: 1.0
  foot_sliding_velocity_weight: -0.2
  foot_lift_height_weight: 1.0

  z_position_target: 0.27
  hinge_position_std: 0.2
  hinge_exceed_limit_ratio: 0.95
  gait_loop_k: 0.25
  feet_state_k: 0.05
  foot_lift_height_target: 0.1

algorithm:
  policy: "MlpPolicy"
  policy_kwargs:
    activation_fn: "ELU"
    net_arch:
      pi: [512, 256, 128]
      vf: [512, 256, 128]
  n_steps: 512
  batch_size: 64
  n_epochs: 10
  learning_rate: 5.e-4
  clip_range: 0.2
  vf_coef: 0.5
  gamma: 0.99
  gae_lambda: 0.95
  device: "cpu"
  verbose: 1

path:
  output: ".\\output\\"
  model_dir_original: ".\\assets\\mujoco_menagerie\\unitree_go1\\"
  model_dir_modified: ".\\assets\\model\\"
  env_py: ".\\src\\env\\unitree_go1.py"
  checkpoint_tree: ".\\output\\checkpoint_tree"

is:
  param_shared: True
  model_camera_modified: True
  model_body_part_visiable: False
  model_obs_space_visiable: False
  model_action_space_visiable: False
