train:
  n_envs: 4
  ctrl_cost_weight: 0.05
  contact_cost_weight: 5.e-4
  forward_reward_weight: 1.
  healthy_reward_weight: 1.
  posture_reward_weight: 1.
  state_reward_weight: 1.
  state_reward_alpha: 0.2
  reset_noise_scale: 0.1
  frame_skip: 5
  max_episode_steps: 1000
  healthy_z_min: 0.18
  healthy_z_max: 0.7
  healthy_pitch_min: -0.785
  healthy_pitch_max: 0.785
  checkpoint_freq: 200000

demo:
  demo_type: "rgb_array" 
  healthy_z_min: 0.195
  healthy_z_max: 0.75
  healthy_pitch_min: -0.524
  healthy_pitch_max: 0.524
  camera_pos: "0 -1.6 1.3"
  camera_xyaxes: "1 0 0 0 1 1"
  mjc_render_width: 150
  mjc_render_height: 150
  plt_n_lines: 1
  plt_x_range: 100

algorithm:
  policy: "MlpPolicy"
  reset_state: "home"
  n_steps: 512
  batch_size: 64
  n_epochs: 10
  learning_rate_init: 5.e-4
  clip_range: 0.2
  vf_coef: 0.5
  gamma: 0.99
  gae_lambda: 0.95
  device: "cpu"
  verbose: 1
  total_timesteps: 1000000

path:
  output: ".\\output\\"
  tensorboard_log: "custom\\"
  model_dir_original: ".\\assets\\mujoco_menagerie\\unitree_go1\\"
  model_dir_modified: ".\\assets\\model\\"
  env_class_py: ".\\src\\env\\unitree_go1.py"
  checkpoint_tree: ".\\output\\checkpoint_tree"

is:
  param_shared: True
  model_body_part_visiable: False
  model_state_def_visiable: False
  model_camera_modified: False