train:
  n_envs: 4
  frame_skip: 5
  reset_noise_scale: 0.1
  max_episode_steps: 1000
  reset_state: "home"
  checkpoint_freq: 204800
  custom_log_freq: 2048

demo:
  demo_type: "rgb_array" 
  camera_pos: "0 -1.6 1.3"
  camera_xyaxes: "1 0 0 0 1 1"
  mjc_render_width: 150
  mjc_render_height: 150
  plt_n_lines: 1
  plt_x_range: 100

reward:
  healthy_z_range: [0.18, 0.7]
  healthy_z_target: 0.27
  healthy_pitch_range: [-0.785, 0.785]
  healthy_reward_weight: 1.
  posture_reward_weight: 1.
  forward_reward_weight: 1.
  gait_reward_alpha: 100.
  state_reward_weight: 1.
  state_reward_alpha: 0.1
  state_reward_hold: 5
  ctrl_cost_weight: 0.05
  contact_cost_weight: 5.e-4
  contact_force_range: [-1.0, 1.0]

algorithm:
  policy: "MlpPolicy"
  n_steps: 512
  batch_size: 64
  n_epochs: 10
  learning_rate_init: 5.e-4
  clip_range: 0.2
  vf_coef: 0.5
  gamma: 0.99
  gae_lambda: 0.95
  device: "cpu"
  verbose: 1
  total_timesteps: 2048000

path:
  output: ".\\output\\"
  model_dir_original: ".\\assets\\mujoco_menagerie\\unitree_go1\\"
  model_dir_modified: ".\\assets\\model\\"
  env_py: ".\\src\\env\\unitree_go1.py"
  checkpoint_tree: ".\\output\\checkpoint_tree"

is:
  param_shared: True
  model_camera_modified: True
  model_body_part_visiable: False
  model_obs_space_visiable: False
  model_action_space_visiable: False

stage:
  
